from app.models._shared import *  # noqa: F401,F403
from app.models._shared import _now, _uuid  # noqa: F401

def _uuid() -> str:
    return str(uuid.uuid4())


def _now() -> datetime:
    return datetime.now(timezone.utc)


class DocumentStatus(str, Enum):
    UPLOADED = "uploaded"
    PARSED = "parsed"
    FAILED = "failed"


class Organization(Base):
    __tablename__ = "organizations"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    name: Mapped[str] = mapped_column(String(200), unique=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)

    documents: Mapped[list["Document"]] = relationship(back_populates="organization", cascade="all, delete-orphan")


# M7b DocumentVersion lifecycle. PENDING_INDEX and INDEX_FAILED are candidate
# states of the two-phase activation protocol (Tx A creates, Qdrant indexing
# runs lock-free, Tx B switches under a CAS); ABANDONED is terminal (a lost
# CAS/authority race) and deliberately does NOT reserve its text_checksum.
DOCUMENT_VERSION_STATES = (
    "PENDING_INDEX",
    "ACTIVE",
    "SUPERSEDED",
    "INDEX_FAILED",
    "ABANDONED",
)
_VERSION_STATES_SQL = ", ".join(f"'{s}'" for s in DOCUMENT_VERSION_STATES)

VERSION_ABANDONED_REASONS = (
    "stale_base",
    "stale_action",
    "authority_lost",
    "checksum_conflict",
)
_ABANDONED_REASONS_SQL = ", ".join(f"'{r}'" for r in VERSION_ABANDONED_REASONS)

CANONICAL_FORMATS = ("pdf", "docx", "txt", "md")
_CANONICAL_FORMATS_SQL = ", ".join(f"'{f}'" for f in CANONICAL_FORMATS)

CHUNK_ID_SCHEMES = ("document_id_v2", "version_id_v3")
_CHUNK_ID_SCHEMES_SQL = ", ".join(f"'{s}'" for s in CHUNK_ID_SCHEMES)


class Document(Base):
    """Logical document identity. Content lives in DocumentVersion rows;
    current_version_id (plain column in the ORM — migration 0014 adds the real
    composite FK on Postgres, 0013 circular-FK pattern) is the SINGLE authority
    for which version serves retrieval. checksum/parser_version/page_count are
    projections of the current version (checksum == its source_checksum, raw
    uploaded/generated bytes) written only on successful parse; a failed upload
    has no version and no mirror values."""

    __tablename__ = "documents"

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    organization_id: Mapped[str] = mapped_column(ForeignKey("organizations.id", ondelete="CASCADE"))
    filename: Mapped[str] = mapped_column(String(300))
    content_type: Mapped[str] = mapped_column(String(100))
    status: Mapped[str] = mapped_column(String(20), default=DocumentStatus.UPLOADED.value)
    error: Mapped[str | None] = mapped_column(Text, nullable=True)
    page_count: Mapped[int] = mapped_column(Integer, default=0)
    checksum: Mapped[str | None] = mapped_column(String(64), nullable=True)
    parser_version: Mapped[str] = mapped_column(String(20), default="")
    current_version_id: Mapped[str | None] = mapped_column(String(36), nullable=True)

    __table_args__ = (
        UniqueConstraint("organization_id", "checksum", name="uq_documents_org_checksum"),
        # Supporting candidate key for the composite ownership FK from
        # document_versions(organization_id, document_id).
        UniqueConstraint("organization_id", "id", name="uq_documents_org_id"),
        # Circular COMPOSITE FK (0014): the current version must be a version OF
        # THIS document — (id, current_version_id) -> (document_id, id) — not
        # merely some existing version, which a single-column FK would allow.
        # use_alter emits it as the same post-hoc ALTER the migration performs,
        # so the models describe the constraint PostgreSQL actually enforces;
        # SQLite (supports_alter=False) skips it, leaving the offline test path
        # unchanged.
        ForeignKeyConstraint(
            ["id", "current_version_id"],
            ["document_versions.document_id", "document_versions.id"],
            name="fk_documents_current_version",
            use_alter=True,
        ),
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)

    organization: Mapped[Organization] = relationship(back_populates="documents")
    versions: Mapped[list["DocumentVersion"]] = relationship(
        back_populates="document",
        cascade="all, delete-orphan",
        order_by="DocumentVersion.version_number",
        foreign_keys="DocumentVersion.document_id",
    )
    # Read-only convenience over the plain current_version_id column (viewonly:
    # the pointer is flipped explicitly in the activation Tx, never via ORM
    # relationship assignment).
    current_version: Mapped["DocumentVersion | None"] = relationship(
        primaryjoin="foreign(Document.current_version_id) == DocumentVersion.id",
        viewonly=True,
        uselist=False,
    )


class DocumentVersion(Base):
    """One immutable content state of a logical document.

    Origins: 'upload' (first upload or explicit human superseding re-upload,
    optionally carrying remediation-artifact lineage) or 'patch' (approved
    anchored patch, TXT/MD only). Pages and chunks are write-once per version;
    superseded versions are never deleted — findings keep citing the exact
    text they were made against.

    source_checksum = sha256 of the exact uploaded/generated bytes (NULL for
    legacy pre-M2 rows); text_checksum = canonical hash of the parsed page
    sequence (services/checksums.py), always present and the basis of patch
    anchoring and the per-document reversion rule (partial unique below —
    ABANDONED rows do not reserve their content).

    source_artifact_id is a plain column here (second circular FK with
    remediation_artifacts; migration 0014 adds the real RESTRICT FK).
    """

    __tablename__ = "document_versions"
    __table_args__ = (
        # Candidate key for composite ownership FKs from pages/chunks.
        UniqueConstraint("document_id", "id", name="uq_document_versions_doc_id"),
        UniqueConstraint(
            "document_id", "version_number", name="uq_document_versions_number"
        ),
        # Ownership: the version's org must be its document's org.
        ForeignKeyConstraint(
            ["organization_id", "document_id"],
            ["documents.organization_id", "documents.id"],
            name="fk_document_versions_org_document",
            ondelete="CASCADE",
        ),
        # Supersession stays within one logical document.
        ForeignKeyConstraint(
            ["document_id", "supersedes_version_id"],
            ["document_versions.document_id", "document_versions.id"],
            name="fk_document_versions_supersedes",
        ),
        CheckConstraint(
            f"state IN ({_VERSION_STATES_SQL})", name="ck_document_versions_state"
        ),
        CheckConstraint(
            "origin IN ('upload', 'patch')", name="ck_document_versions_origin"
        ),
        CheckConstraint(
            f"canonical_format IN ({_CANONICAL_FORMATS_SQL})",
            name="ck_document_versions_format",
        ),
        CheckConstraint(
            f"chunk_id_scheme IN ({_CHUNK_ID_SCHEMES_SQL})",
            name="ck_document_versions_chunk_scheme",
        ),
        CheckConstraint("version_number >= 1", name="ck_document_versions_number_min"),
        # Lineage coherence: exactly the first version has no predecessor.
        CheckConstraint(
            "(version_number = 1 AND supersedes_version_id IS NULL) "
            "OR (version_number > 1 AND supersedes_version_id IS NOT NULL)",
            name="ck_document_versions_lineage",
        ),
        # A patch-born version is generated bytes: both byte-level fields set.
        CheckConstraint(
            "origin != 'patch' OR (source_checksum IS NOT NULL AND byte_size IS NOT NULL)",
            name="ck_document_versions_patch_bytes",
        ),
        # Activation-state coherence: terminal/settled states carry no lease;
        # ABANDONED requires its reason and nothing else may carry one;
        # INDEX_FAILED must say why.
        CheckConstraint(
            "(state IN ('ACTIVE', 'SUPERSEDED', 'ABANDONED') AND activation_token IS NULL) "
            "OR state IN ('PENDING_INDEX', 'INDEX_FAILED')",
            name="ck_document_versions_settled_no_token",
        ),
        CheckConstraint(
            "(state = 'ABANDONED' AND abandoned_reason IS NOT NULL) "
            "OR (state != 'ABANDONED' AND abandoned_reason IS NULL)",
            name="ck_document_versions_abandoned_reason",
        ),
        CheckConstraint(
            f"abandoned_reason IS NULL OR abandoned_reason IN ({_ABANDONED_REASONS_SQL})",
            name="ck_document_versions_abandoned_taxonomy",
        ),
        CheckConstraint(
            "state != 'INDEX_FAILED' OR activation_error IS NOT NULL",
            name="ck_document_versions_index_failed_error",
        ),
        CheckConstraint(
            "state NOT IN ('ACTIVE', 'SUPERSEDED') OR activation_error IS NULL",
            name="ck_document_versions_settled_no_error",
        ),
        # One ACTIVE version per logical document (DB-enforced invariant).
        Index(
            "uq_document_versions_one_active",
            "document_id",
            unique=True,
            postgresql_where=text("state = 'ACTIVE'"),
            sqlite_where=text("state = 'ACTIVE'"),
        ),
        # Reversion rule: identical content per document conflicts UNLESS the
        # older row is a terminal ABANDONED candidate (which must not reserve
        # its content against a fresh, newly authorized attempt).
        Index(
            "uq_document_versions_live_text",
            "document_id",
            "text_checksum",
            unique=True,
            postgresql_where=text("state != 'ABANDONED'"),
            sqlite_where=text("state != 'ABANDONED'"),
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    document_id: Mapped[str] = mapped_column(
        ForeignKey("documents.id", ondelete="CASCADE"), index=True
    )
    organization_id: Mapped[str] = mapped_column(String(36))
    version_number: Mapped[int] = mapped_column(Integer)
    state: Mapped[str] = mapped_column(String(20))
    source_checksum: Mapped[str | None] = mapped_column(String(64), nullable=True)
    text_checksum: Mapped[str] = mapped_column(String(64))
    parser_version: Mapped[str] = mapped_column(String(20))
    chunker_version: Mapped[str] = mapped_column(String(20))
    chunk_id_scheme: Mapped[str] = mapped_column(String(20))
    page_count: Mapped[int] = mapped_column(Integer)
    origin: Mapped[str] = mapped_column(String(20))
    supersedes_version_id: Mapped[str | None] = mapped_column(String(36), nullable=True)
    # Corrective-action lineage (circular FK, added post-hoc by 0014).
    # ON DELETE RESTRICT is the guard that stops a cited artifact being removed
    # out from under its version — declared here, not only in the migration.
    source_artifact_id: Mapped[str | None] = mapped_column(
        ForeignKey(
            "remediation_artifacts.id",
            use_alter=True,
            name="fk_document_versions_source_artifact",
            ondelete="RESTRICT",
        ),
        nullable=True,
    )
    canonical_format: Mapped[str] = mapped_column(String(10))
    filename: Mapped[str] = mapped_column(String(300))
    reported_mime: Mapped[str | None] = mapped_column(String(100), nullable=True)
    byte_size: Mapped[int | None] = mapped_column(Integer, nullable=True)
    # Activation lease: token-fenced two-phase PG<->Qdrant switch (M7b §5).
    activation_token: Mapped[str | None] = mapped_column(String(36), nullable=True)
    activation_started_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    activation_heartbeat_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    activation_error: Mapped[str | None] = mapped_column(Text, nullable=True)
    abandoned_reason: Mapped[str | None] = mapped_column(String(30), nullable=True)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_now)

    document: Mapped[Document] = relationship(
        back_populates="versions", foreign_keys=[document_id]
    )
    pages: Mapped[list["DocumentPage"]] = relationship(
        back_populates="version",
        cascade="all, delete-orphan",
        order_by="DocumentPage.page_number",
        foreign_keys="DocumentPage.document_version_id",
    )
    chunks: Mapped[list["Chunk"]] = relationship(
        back_populates="version",
        cascade="all, delete-orphan",
        foreign_keys="Chunk.document_version_id",
    )


class DocumentPage(Base):
    """Parsed text, one row per page (PDF) or per document (DOCX/TXT), owned
    by ONE DocumentVersion (write-once: a version's text never changes).

    This is the provenance anchor: chunks (M2) and citations (M3+) reference
    page_number + character offsets into `text`. document_id is retained as an
    immutable denormalization; the composite FK proves both columns name the
    same logical document.
    """

    __tablename__ = "document_pages"
    __table_args__ = (
        ForeignKeyConstraint(
            ["document_id", "document_version_id"],
            ["document_versions.document_id", "document_versions.id"],
            name="fk_document_pages_version",
            ondelete="CASCADE",
        ),
        UniqueConstraint(
            "document_version_id", "page_number", name="uq_document_pages_version_page"
        ),
    )

    id: Mapped[str] = mapped_column(String(36), primary_key=True, default=_uuid)
    document_id: Mapped[str] = mapped_column(ForeignKey("documents.id", ondelete="CASCADE"))
    document_version_id: Mapped[str] = mapped_column(String(36), index=True)
    page_number: Mapped[int] = mapped_column(Integer)
    text: Mapped[str] = mapped_column(Text)

    document: Mapped[Document] = relationship(foreign_keys=[document_id])
    version: Mapped[DocumentVersion] = relationship(
        back_populates="pages", foreign_keys=[document_version_id]
    )


class Chunk(Base):
    """Retrieval unit over a document page span, owned by ONE DocumentVersion.

    Chunking is write-once per version: once a version has chunk rows they are
    reused verbatim (never recomputed), so pre-M7b content-addressed ids
    (scheme document_id_v2) survive the restructuring and
    findings.matched_chunk_id stays resolvable forever. New versions use the
    version-scoped scheme (version_id_v3, services/chunking.py).
    char_start/char_end slice the owning page's text exactly:
    text == page_text[char_start:char_end].
    """

    __tablename__ = "chunks"
    __table_args__ = (
        ForeignKeyConstraint(
            ["document_id", "document_version_id"],
            ["document_versions.document_id", "document_versions.id"],
            name="fk_chunks_version",
            ondelete="CASCADE",
        ),
    )

    id: Mapped[str] = mapped_column(String(64), primary_key=True)
    document_id: Mapped[str] = mapped_column(
        ForeignKey("documents.id", ondelete="CASCADE"), index=True
    )
    document_version_id: Mapped[str] = mapped_column(String(36), index=True)
    page_number: Mapped[int] = mapped_column(Integer)
    char_start: Mapped[int] = mapped_column(Integer)
    char_end: Mapped[int] = mapped_column(Integer)
    text: Mapped[str] = mapped_column(Text)

    document: Mapped[Document] = relationship(foreign_keys=[document_id])
    version: Mapped[DocumentVersion] = relationship(
        back_populates="chunks", foreign_keys=[document_version_id]
    )
