"""Canonical content checksums for DocumentVersion (M7b).

Two distinct hashes, never interchangeable:
  - source_checksum: sha256 over the EXACT uploaded/generated bytes — the
    org-level dedup / corpus-baseline semantics (documents.checksum mirror).
  - text_checksum (here): deterministic hash over the parsed page sequence,
    always computable for parsed content (including legacy rows whose bytes
    were never stored). Basis of patch anchoring (base_text_checksum) and the
    per-document reversion rule.

The encoding is length-prefixed, NOT delimiter-joined: a delimiter could occur
inside page text and let two different page splits collide. Fixed layout:
  sha256( u32be(page_count)
          || for each page: u32be(page_number) || u32be(len(utf8)) || utf8 )
The same helper is used by the migration backfill, upload, patch creation and
tests — never reimplement it inline.
"""

import hashlib
import struct


def text_checksum(pages: list[str]) -> str:
    """Canonical sha256 over an ordered page-text sequence (1-based pages)."""
    h = hashlib.sha256()
    h.update(struct.pack(">I", len(pages)))
    for number, page in enumerate(pages, start=1):
        data = page.encode("utf-8")
        h.update(struct.pack(">I", number))
        h.update(struct.pack(">I", len(data)))
        h.update(data)
    return h.hexdigest()
